name: ðŸš€ Deploy to Dev (PM2)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy NestJS to Dev Server
    runs-on: self-hosted

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@172.25.100.201 << 'EOF'
            set -x  # Esto muestra los comandos ejecutados y sus salidas
            echo "ðŸ“ Entrando al servidor"
            cd /var/www/html/tuempleo.cl
            echo "ðŸ“¥ Haciendo pull"
            git pull origin dev
            echo "ðŸ“¦ Instalando dependencias"
            npm install
            echo "ðŸ—ï¸ Compilando"
            npm run build
            echo "ðŸš€ Reiniciando con PM2"
            pm2 reload ecosystem.config.js --only tuempleobackend
          EOF
