name: Deploy to Dev Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy NestJS to Dev Server
    runs-on: self-hosted

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@172.25.100.201 << 'EOF'
            set -x  # Esto muestra los comandos ejecutados y sus salidas

            # Verificando versiones de node y pm2
            echo "ðŸš€ Verificando la versiÃ³n de Node.js"
            node -v
            echo "ðŸš€ Verificando la versiÃ³n de PM2"
            pm2 -v

            echo "ðŸ“ Entrando al servidor"
            cd /var/www/html/tuempleo.cl || { echo "Fallo al entrar al directorio"; exit 1; }

            echo "ðŸ“¥ Haciendo pull"
            git pull origin dev || { echo "Fallo al hacer git pull"; exit 1; }

            echo "ðŸ“¦ Instalando dependencias"
            npm install || { echo "Fallo al instalar dependencias"; exit 1; }

            echo "ðŸ—ï¸ Compilando"
            npm run build || { echo "Fallo al compilar"; exit 1; }

            echo "ðŸš€ Reiniciando con PM2"
            pm2 restart tuempleo.cl  || { echo "Fallo al reiniciar PM2"; exit 1; }
          EOF
  